version: '3'

volumes:
  app-volume:

services:
  logs_template: &logs_template
    image: alpine
    logging:
      options:
        max-size: "200k"
        max-file: "7"

  envs: &envs_template
    image: alpine
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DJ_DEFAULT_FROM_EMAIL=${DJ_DEFAULT_FROM_EMAIL}
      - DJ_EMAIL_HOST_USER=${DJ_EMAIL_HOST_USER}
      - DJ_EMAIL_HOST_PASSWORD=${DJ_EMAIL_HOST_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}

  redis:
    image: "redis:alpine"
    ports:
    - 6379:6379

  celery:
    build: .
    <<: *envs_template
    command: celery -A ksardas worker --loglevel=debug --concurrency=4
    depends_on:
    - redis
    volumes:
    - app-volume:/ksardas

  web:
    <<: *logs_template
    container_name: web_django
    <<: *envs_template
    build: .
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    volumes:
      - app-volume:/ksardas
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
