version: '3'

services:
  logs_template: &logs_template
    image: alpine
    logging:
      options:
        max-size: "200k"
        max-file: "7"

  web:
    <<: *logs_template
    container_name: web_django
    build: .
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    expose:
      - 8000
    ports:
      - 80:8000
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
