# Generated by Django 3.0.2 on 2021-02-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charbase',
            name='bonds',
            field=models.CharField(max_length=32, null=True, verbose_name='Привязанности'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='flaws',
            field=models.CharField(max_length=32, null=True, verbose_name='Пороки'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='ideals',
            field=models.CharField(max_length=32, null=True, verbose_name='Идеалы'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='pers_traits',
            field=models.CharField(max_length=32, null=True, verbose_name='Персональные черты'),
        ),
    ]
