# Generated by Django 3.0.2 on 2021-02-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210209_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charbase',
            name='expirence_modifier',
        ),
        migrations.RemoveField(
            model_name='mobbase',
            name='expirence_modifier',
        ),
        migrations.AddField(
            model_name='charbase',
            name='acrobatics',
            field=models.CharField(default='', max_length=8, verbose_name='Акробатика(лов)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='animal',
            field=models.CharField(default='', max_length=8, verbose_name='Уход за животными(мдр)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='arcana',
            field=models.CharField(default='', max_length=8, verbose_name='Магия(инт)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='athletics',
            field=models.CharField(default='', max_length=8, verbose_name='Атлетика(сил)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='deception',
            field=models.CharField(default='', max_length=8, verbose_name='Обман(хар)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='history',
            field=models.CharField(default='', max_length=8, verbose_name='История(инт)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='insight',
            field=models.CharField(default='', max_length=8, verbose_name='Проницательность(мдр)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='intimidation',
            field=models.CharField(default='', max_length=8, verbose_name='Запугивание(хар)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='investigation',
            field=models.CharField(default='', max_length=8, verbose_name='Изучение'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='medicine',
            field=models.CharField(default='', max_length=8, verbose_name='Медицина(мдр)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='nature',
            field=models.CharField(default='', max_length=8, verbose_name='Природа(инт)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='perception',
            field=models.CharField(default='', max_length=8, verbose_name='Внимательность(мдр.)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='performance',
            field=models.CharField(default='', max_length=8, verbose_name='Выступление(хар)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='persuasion',
            field=models.CharField(default='', max_length=8, verbose_name='Убеждение(хар)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='religion',
            field=models.CharField(default='', max_length=8, verbose_name='Религия(инт)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='sleightofHand',
            field=models.CharField(default='', max_length=8, verbose_name='Ловкость рук(лов)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='stealth',
            field=models.CharField(default='', max_length=8, verbose_name='Скрытность(лов)'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='survival',
            field=models.CharField(default='', max_length=8, verbose_name='Выживание(мдр)'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='abilities',
            field=models.TextField(default='', verbose_name='способности'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='actions',
            field=models.TextField(default='', verbose_name='действия'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='age',
            field=models.IntegerField(default=21, verbose_name='Возраст персонажа'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='armor_class',
            field=models.IntegerField(default=0, verbose_name='Класс доспеха'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='bonds',
            field=models.CharField(default='', max_length=32, verbose_name='Привязанности'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='char_history',
            field=models.TextField(default='', verbose_name='Предыстория'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='copper_count',
            field=models.IntegerField(default=0, verbose_name='Медь персонажа'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='eyes',
            field=models.CharField(default='', max_length=20, verbose_name='Цвет глаз'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='feelings',
            field=models.TextField(default='', verbose_name='чувства'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='flaws',
            field=models.CharField(default='', max_length=32, verbose_name='Пороки'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='gold_count',
            field=models.IntegerField(default=0, verbose_name='Золото персонажа'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='hair',
            field=models.CharField(default='', max_length=20, verbose_name='Цвет волос'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='height',
            field=models.IntegerField(default=175, verbose_name='Рост персонажа'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='hitpoints_curr',
            field=models.IntegerField(default=0, verbose_name='Текущие хиты'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='hitpoints_max',
            field=models.IntegerField(default=0, verbose_name='Максимум хитов'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='hitpoints_str',
            field=models.CharField(default='', max_length=32, verbose_name='Кости хитов'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='hitpoints_temp',
            field=models.IntegerField(default=0, verbose_name='Временные хиты'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='ideals',
            field=models.CharField(default='', max_length=32, verbose_name='Идеалы'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='initiative',
            field=models.IntegerField(default=0, verbose_name='Инициатива'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='inspiration',
            field=models.IntegerField(default=0, verbose_name='Вдохновение'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='pers_traits',
            field=models.CharField(default='', max_length=32, verbose_name='Персональные черты'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='prof_bonus',
            field=models.IntegerField(default=0, verbose_name='Бонус мастерства'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='saving_throws',
            field=models.TextField(default='', verbose_name='спасброски'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='silver_count',
            field=models.IntegerField(default=0, verbose_name='Серебро персонажа'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='skills',
            field=models.TextField(default='', verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='skin',
            field=models.CharField(default='', max_length=20, verbose_name='Цвет кожы'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='speed',
            field=models.CharField(default='', max_length=32, verbose_name='Скорость персонажа'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='weight',
            field=models.IntegerField(default=60, verbose_name='Вес персонажа'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='world_view',
            field=models.CharField(default='', max_length=32, verbose_name='Мировозрение'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='abilities',
            field=models.TextField(default='', verbose_name='способности'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='actions',
            field=models.TextField(default='', verbose_name='действия'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='armor_class',
            field=models.IntegerField(default=0, verbose_name='Класс доспеха'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='armor_class_str',
            field=models.CharField(default='', max_length=255, verbose_name='описание доспеха'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='danger',
            field=models.CharField(default='', max_length=32, verbose_name='опасность'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='feelings',
            field=models.TextField(default='', verbose_name='чувства'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='hitpoints_max',
            field=models.IntegerField(default=0, verbose_name='Максимум хитов'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='hitpoints_str',
            field=models.CharField(default='', max_length=32, verbose_name='Кости хитов'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='material_source',
            field=models.CharField(default='', max_length=255, verbose_name='источник материала'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='mob_type',
            field=models.CharField(default='', max_length=255, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='saving_throws',
            field=models.TextField(default='', verbose_name='спасброски'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='size',
            field=models.CharField(default='', max_length=255, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='skills',
            field=models.TextField(default='', verbose_name='навыки'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='speed',
            field=models.CharField(default='', max_length=32, verbose_name='Скорость персонажа'),
        ),
        migrations.AlterField(
            model_name='mobbase',
            name='world_view',
            field=models.CharField(default='', max_length=32, verbose_name='Мировозрение'),
        ),
    ]
