# Generated by Django 3.0.2 on 2021-02-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210212_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charbase',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='charbase',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='charbase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='charbase',
            name='feelings',
        ),
        migrations.AddField(
            model_name='mobbase',
            name='acrobatics',
            field=models.CharField(default='', max_length=8, verbose_name='Акробатика(лов)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='animal',
            field=models.CharField(default='', max_length=8, verbose_name='Уход за животными(мдр)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='arcana',
            field=models.CharField(default='', max_length=8, verbose_name='Магия(инт)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='athletics',
            field=models.CharField(default='', max_length=8, verbose_name='Атлетика(сил)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='deception',
            field=models.CharField(default='', max_length=8, verbose_name='Обман(хар)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='history',
            field=models.CharField(default='', max_length=8, verbose_name='История(инт)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='insight',
            field=models.CharField(default='', max_length=8, verbose_name='Проницательность(мдр)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='intimidation',
            field=models.CharField(default='', max_length=8, verbose_name='Запугивание(хар)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='investigation',
            field=models.CharField(default='', max_length=8, verbose_name='Расследование(инт)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='medicine',
            field=models.CharField(default='', max_length=8, verbose_name='Медицина(мдр)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='nature',
            field=models.CharField(default='', max_length=8, verbose_name='Природа(инт)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='perception',
            field=models.CharField(default='', max_length=8, verbose_name='Внимательность(мдр.)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='performance',
            field=models.CharField(default='', max_length=8, verbose_name='Выступление(хар)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='persuasion',
            field=models.CharField(default='', max_length=8, verbose_name='Убеждение(хар)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='religion',
            field=models.CharField(default='', max_length=8, verbose_name='Религия(инт)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='sleightofHand',
            field=models.CharField(default='', max_length=8, verbose_name='Ловкость рук(лов)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_chrarisma',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_chrarisma_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_constitution',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_constitution_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_dexterity',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_dexterity_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_intellegence',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_intellegence_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_strength',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_strength_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_wisdom',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='st_wisdom_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='stealth',
            field=models.CharField(default='', max_length=8, verbose_name='Скрытность(лов)'),
        ),
        migrations.AddField(
            model_name='mobbase',
            name='survival',
            field=models.CharField(default='', max_length=8, verbose_name='Выживание(мдр)'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='investigation',
            field=models.CharField(default='', max_length=8, verbose_name='Расследование(инт)'),
        ),
    ]
