# Generated by Django 3.0.2 on 2021-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210212_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='charbase',
            name='attacks_spellc',
            field=models.TextField(default='', verbose_name='Атаки и заклинания'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='equipment',
            field=models.TextField(default='', verbose_name='Снаряжение'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='features_traits',
            field=models.TextField(default='', verbose_name='Умения и особенности'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='profi_languages',
            field=models.TextField(default='', verbose_name='Прочие владения и языки'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='psv_perception',
            field=models.CharField(default='', max_length=32, verbose_name='пассивная мудрость (внимательность)'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='char_history',
            field=models.CharField(default='', max_length=32, verbose_name='Предыстория'),
        ),
    ]
