# Generated by Django 4.0.6 on 2022-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210216_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobBase',
        ),
        migrations.RenameField(
            model_name='charbase',
            old_name='attacks_spellc',
            new_name='attacks_and_spell_casting',
        ),
        migrations.RenameField(
            model_name='charbase',
            old_name='profi_languages',
            new_name='prof_and_languages',
        ),
        migrations.RenameField(
            model_name='charbase',
            old_name='sleightofHand',
            new_name='sleight_of_hand',
        ),
        migrations.RemoveField(
            model_name='charbase',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='charbase',
            name='hitpoints_str',
        ),
        migrations.RemoveField(
            model_name='charbase',
            name='saving_throws',
        ),
        migrations.RemoveField(
            model_name='charbase',
            name='skills',
        ),
        migrations.AddField(
            model_name='charbase',
            name='additional_features_traits',
            field=models.TextField(default='', verbose_name='Дополнительные особенности и черты'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='allies_and_org',
            field=models.TextField(default='', verbose_name='Альянсы и организации'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='allies_and_org_symbol',
            field=models.ImageField(blank=True, null=True, upload_to='symbols/', verbose_name='Символ'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='allies_and_org_symbol_name',
            field=models.CharField(default='', max_length=24, verbose_name='Название символа'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='char_backstory',
            field=models.TextField(default='', verbose_name='Предыстория персонажа'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='hit_dice',
            field=models.CharField(default='', max_length=8, verbose_name='Кости хитов'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='hit_dice_total',
            field=models.CharField(default='', max_length=8, verbose_name='Кости хитов макс.'),
        ),
        migrations.AddField(
            model_name='charbase',
            name='st_fail_death_box1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='st_fail_death_box2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='st_fail_death_box3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='st_succ_death_box1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='st_succ_death_box2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='st_succ_death_box3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='treasure',
            field=models.TextField(default='', verbose_name='Сокровища'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='bonds',
            field=models.TextField(default='', verbose_name='Привязанности'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='chrarisma_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор харизмы'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='constitution_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор телосложения'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='dexterity_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор ловкости'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='flaws',
            field=models.TextField(default='', verbose_name='Пороки'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='ideals',
            field=models.TextField(default='', verbose_name='Идеалы'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='intellegence_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор интеллекта'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='pers_traits',
            field=models.TextField(default='', verbose_name='Персональные черты'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='psv_perception',
            field=models.CharField(default='', max_length=32, verbose_name='пассивная мудрость (восприятие)'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='strength_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор силы'),
        ),
        migrations.AlterField(
            model_name='charbase',
            name='wisdom_modifier',
            field=models.IntegerField(default=0, verbose_name='Модификатор мудрости'),
        ),
    ]
