# Generated by Django 4.0.6 on 2022-08-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_charbase_spell_attack_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charbase',
            name='acrobatics_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='animal_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='arcana_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='athletics_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='deception_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='history_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='insight_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='intimidation_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='investigation_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='medicine_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='nature_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='perception_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='performance_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='persuasion_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='religion_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='sleight_of_hand_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='stealth_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charbase',
            name='survival_box',
            field=models.BooleanField(default=False),
        ),
    ]
